import { ruPlural } from "@/lib/plural";

export const content = {
  site: {
    name: "Skelet",
    shortName: "Skelet",
    tagline: "Сообщество (тестовая ниша)",
    description: "Тестовый инстанс скелета. Замените текстами своей ниши в theme/content.ts.",
  },
  nav: {
    home: "Лента",
    new: "Написать пост",
    tags: "Темы",
    drafts: "Драфты",
    profile: "Профиль",
    login: "Войти",
  },
  feed: {
    prev: "← Назад",
    next: "Вперёд →",
    page: (n: number) => `Страница ${n}`,
    readingTime: (min: number) => `${min} мин чтения`,
  },
  auth: {
    loginTitle: "Войти",
    loginSubtitle: "Выберите сервис для входа",
    noProviders: "OAuth-провайдеры не настроены. Заполните CLIENT_ID/SECRET в .env.",
    signOut: "Выйти",
    chooseUsername: "Выбери ник",
    welcomeTitle: "Придумайте username",
    welcomeHint: "3–20 символов: латиница, цифры, _ и -. Это часть адреса вашего профиля.",
    welcomeSubmit: "Сохранить",
    errorFormat: "Неправильный формат username",
    errorReserved: "Этот username зарезервирован",
    errorTaken: "Этот username уже занят",
    backToHome: "На главную",
  },
  empty: {
    feed: "Пока нет постов. Будьте первым!",
    drafts: "У вас нет черновиков",
    tag: "Постов по этой теме пока нет",
    userFeed: "У автора пока нет публикаций.",
  },
  tags: {
    indexTitle: "Все темы",
    indexEmpty: "Темы ещё не созданы.",
    postCount: (n: number) => `${n} постов`,
  },
  profile: {
    registeredSince: (monthYear: string) => `с ${monthYear}`,
    postsCount: (n: number) => `${n} постов`,
  },
  footer: {
    about: "О проекте",
    rules: "Правила",
    contacts: "Контакты",
  },
  consent: {
    text: "Сайт использует cookies для аналитики.",
    accept: "Принять",
    decline: "Только необходимые",
  },
  comments: {
    heading: "Обсуждение",
    countLabel: (n: number) => `${n} ${ruPlural(n, "комментарий", "комментария", "комментариев")}`,
    empty: "Будьте первым, кто оставит комментарий.",
    placeholder: "Ваш комментарий...",
    submit: "Отправить",
    edit: "Изменить",
    save: "Сохранить",
    cancel: "Отмена",
    delete: "Удалить",
    deleteConfirm: "Удалить комментарий?",
    deletedByAuthor: "Комментарий удалён автором",
    deletedByAdmin: "Комментарий удалён администратором",
    bannedAuthor: "автор заблокирован",
    loginToComment: "Войдите, чтобы оставить комментарий",
    editWindowClosed: "Окно редактирования (15 минут) закрыто.",
    rateLimitHit: (sec: number) => `Слишком часто. Попробуйте через ${sec} с.`,
    charCount: (n: number) => `${n} / 2000`,
    reply: "Ответить",
  },
  moderation: {
    postMenuLabel: "Действия модератора",
    hidePost: "Скрыть пост",
    unhidePost: "Показать пост",
    deletePost: "Удалить пост",
    deletePostConfirm: "Удалить пост? Восстановить сможете в админ-меню.",
    restorePost: "Восстановить",
    banUser: "Заблокировать автора",
    banReasonLabel: "Причина блокировки (обязательно)",
    banReasonPlaceholder: "Минимум 5 символов",
    banSubmit: "Заблокировать",
    unbanUser: "Разблокировать",
    hiddenByAdmin: "Скрыт администратором",
    hiddenBannerOwner: "Этот пост скрыт администратором. Он недоступен публично.",
    hiddenBannerAdmin: (username: string) => `Скрыт администратором @${username}.`,
    hiddenBannerAdminUnknown: "Скрыт администратором.",
    adminDeleteComment: "Удалить",
    adminRestoreComment: "Восстановить",
    userMenuLabel: "Действия модератора над пользователем",
    unbanUserConfirm: "Разблокировать этого пользователя?",
  },
  banned: {
    heading: "Ваша учётная запись заблокирована",
    reasonLabel: "Причина:",
    noReason: "Причина не указана.",
    contact: "Для подробной информации напишите: test@mail.ru",
    logout: "Выйти",
  },
  write: {
    label: "Написать",
    cta: "Написать пост",
  },
  copyright: `© ${new Date().getFullYear()} Skelet`,
} as const;

export type ContentSchema = typeof content;
